Estrutura
Ironhack-SAO-PTWD-Jun-2022/randomizer pull request #12
Opened 2022-09-02 00:52 UTC by joaopaulobco

Importei o Router no index.js e estruturei o Routes/Route no App.js, qualquer erro favor me ajudar a corrigir.

2022-09-02 01:23 UTC, D-Kunrath requested changes
O componente `<Route />` só é usado para os elementos q vão mudar de acordo com a URL, ou seja, as páginas.

Os elementos Navbar, Sidebar e Footer não mudam de acordo com a URL.

Para q se use esses elementos basta por **fora** do `<Routes>...</Routes>`

2022-09-02 01:23 UTC, D-Kunrath commented on src/App.js
> +          <Route path="/" element={<Navbar />} />
A navbar não precisa de rota! As rotas são apenas para os elementos q mudam de acordo com a URL!

2022-09-02 01:23 UTC, D-Kunrath commented on src/App.js
> +            <Route path="/Sidebar" element={<Sidebar />} />
a sidebar não precisa de rota! As rotas são apenas para os elementso q mudam de acordo com a URL!

2022-09-02 01:23 UTC, D-Kunrath commented on src/App.js
> +            <Route path="/Container" element={<Container />} />
o "Container" não existe, ele é apenas um nome estrutural de onde ficam as nossas páginas, ou seja, os elementos q vão mudar de acordo com a URL.

2022-09-02 01:23 UTC, D-Kunrath commented on src/App.js
> +          <Route path="/Footer" element={<Footer />} />
o Footer não precisa de rota! Mesmo motivo dos anteriores!

2022-09-03 15:22 UTC, joaopaulobco commented on src/App.js
> +          <Route path="/" element={<Navbar />} />
Feito

2022-09-03 15:22 UTC, joaopaulobco commented on src/App.js
> +            <Route path="/Sidebar" element={<Sidebar />} />
feito

2022-09-03 15:22 UTC, joaopaulobco commented on src/App.js
> +            <Route path="/Container" element={<Container />} />
feito

2022-09-03 15:22 UTC, joaopaulobco commented on src/App.js
> +          <Route path="/Footer" element={<Footer />} />
corrigido

2022-09-03 17:55 UTC, D-Kunrath approved these changes

2022-09-03 17:55 UTC, D-Kunrath commented on src/App.css
> +
se não tem nada nesse cara, pode remover!

2022-09-03 17:55 UTC, merged

2022-09-03 18:22 UTC, joaopaulobco commented on src/App.css
> +
Ok